server:
  port: 50202
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true
spring:
  application:
    name: test-govern-zuul
zuul:
  prefix: /api
  routes:
    test:
      path: /test/**
      url: http://localhost:50101/
